project_id = "uqinkeatbviivewmcxei"

[functions.admin-users]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-transcribe]
verify_jwt = false

[functions.vita-chat]
verify_jwt = false

[functions.whatsapp-welcome]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.trial-started-notification]
verify_jwt = false

[functions.trial-reminder]
verify_jwt = false

[functions.trial-activated-notification]
verify_jwt = false


[functions.create-customer-portal]
verify_jwt = false
